#!/usr/bin/env python3
"""Verify public entries themselves drain their fixture processes, including stdin scripts."""
import json
import os
from pathlib import Path
import secrets
import shutil
import signal
import subprocess
import sys
import tempfile
import time

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / '.qwb-tmp'
BASE.mkdir(exist_ok=True)
WIRE = str(ROOT / 'tests/fixtures/herdr/wire-server.py')


def snapshot():
    probe = subprocess.Popen(['/bin/ps', '-axo', 'pid=,ppid=,pgid=,stat=,command='],
                             stdout=subprocess.PIPE)
    output, _ = probe.communicate()
    assert probe.returncode == 0
    return [row for line in output.decode('utf-8', errors='replace').splitlines() if (row := line.split(None, 4))
            and int(row[0]) != probe.pid]


def check(command, interrupt=False, ready='wire'):
    groups = set()
    observed = {}
    with tempfile.TemporaryDirectory(prefix='observe-', dir=BASE) as temporary:
        observer = Path(temporary)
        wire_record = observer / 'wire.json'
        shim = observer / 'python3'
        # Observe the actual exec PID/group, without starting another supervisor around the entry.
        shim.write_text(f'''#!{sys.executable}
import json,os,sys
from pathlib import Path
if sys.argv[1:3]==['-B',os.environ['ENTRY_WIRE']]:
    Path(os.environ['ENTRY_WIRE_RECORD']).write_text(json.dumps(dict(pid=os.getpid(),ppid=os.getppid(),pgid=os.getpgrp(),argv=sys.argv[1:])))
os.execv(sys.executable,[sys.executable,*sys.argv[1:]])
''')
        shim.chmod(0o755)
        env = dict(os.environ, PATH=str(observer) + ':' + os.environ['PATH'],
                   ENTRY_WIRE=WIRE, ENTRY_WIRE_RECORD=str(wire_record))
        before = set(BASE.iterdir())
        with tempfile.TemporaryFile(dir=BASE) as output:
            process = subprocess.Popen(command, cwd=ROOT, env=env, stdout=output,
                                       stderr=subprocess.STDOUT, start_new_session=True)
            groups.add(process.pid)
            try:
                deadline = time.monotonic() + 60
                sent = False
                while process.poll() is None:
                    table = snapshot()
                    owned = {int(row[0]) for row in table if int(row[2]) in groups}
                    while True:
                        grown = owned | {int(row[0]) for row in table if int(row[1]) in owned}
                        if grown == owned:
                            break
                        owned = grown
                    for row in table:
                        if int(row[0]) in owned:
                            groups.add(int(row[2]))
                            observed[int(row[0])] = row
                    text = os.pread(output.fileno(), os.fstat(output.fileno()).st_size, 0).decode(
                        'utf-8', 'backslashreplace')
                    if ready == 'wire':
                        reached = wire_record.exists()
                    elif ready == 'handoff':
                        reached = 'PASS 跨交付崩溃仍有持久待办' in text
                    else:
                        reached = any(int(row[0]) in owned and str(ROOT) in row[4]
                                      and ('/bin/qwb-' in row[4] or '/qwbuddy/bin/qwb-' in row[4])
                                      for row in table)
                    if interrupt and reached and not sent:
                        time.sleep(.15)
                        process.send_signal(signal.SIGTERM)
                        sent = True
                    assert time.monotonic() < deadline, (command, 'entry timed out', text[-2000:])
                    time.sleep(.02)
                rc = process.wait()
                assert rc == (143 if interrupt else 0), (command, rc)
                assert not interrupt or sent, 'entry exited before its interruption point'
                wire = json.loads(wire_record.read_text()) if wire_record.exists() else None
                assert ready != 'wire' or wire, ('wire fixture was never launched', command)
                if wire:
                    groups.add(wire['pgid'])
                if interrupt:
                    time.sleep(5)
                survivors = [row for row in snapshot() if int(row[2]) in groups
                             and not row[3].startswith('Z')]
                text = os.pread(output.fileno(), os.fstat(output.fileno()).st_size, 0).decode(
                    'utf-8', 'backslashreplace')
                assert not survivors, (command, 'owned processes survived', survivors)
                assert not any(line.startswith('rm:') for line in text.splitlines()), text
                assert set(BASE.iterdir()) == before, (command, 'temporary directory survived',
                    {str(p): [str(q.relative_to(p)) for q in list(p.rglob('*'))[:20]]
                     for p in set(BASE.iterdir()) - before})
                assert not (ROOT / 'tests/__pycache__').exists(), 'test imports generated bytecode'
                print(json.dumps(dict(command=command, term=interrupt, rc=rc,
                                      recorded_groups=sorted(groups), wire=wire, survivors=survivors,
                                      new_directories=[], bytecode=False, tail=text.splitlines()[-5:]),
                                 ensure_ascii=False), flush=True)
            finally:
                if process.poll() is None:
                    process.terminate()
                    process.wait(timeout=20)
                # On a failed check, stop only exact observed owned process incarnations.
                if wire_record.exists():
                    wire = json.loads(wire_record.read_text())
                    groups.add(wire['pgid'])
                for row in snapshot():
                    old = observed.get(int(row[0]))
                    owned_wire = wire_record.exists() and int(row[0]) == wire['pid'] and int(row[2]) == wire['pgid']
                    if owned_wire or (old and row[2] == old[2] and row[4] == old[4] and int(row[2]) in groups):
                        try:
                            os.kill(int(row[0]), signal.SIGTERM)
                        except ProcessLookupError:
                            pass


def check_full_gate():
    # Retry windows are mocked: scheduling backoff must never weaken the 2s measurement.
    import contextlib
    import importlib.util
    import io
    from unittest.mock import patch
    spec = importlib.util.spec_from_file_location('subscribe_reap', ROOT / 'tests/subscribe-reap.py')
    reap = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(reap)
    for misses in (5, 2):
        outcomes = [reap.MissedWindow(dict(reader_age=2.1)) for _ in range(misses)]
        if misses < 5:
            outcomes.append(dict(reader_age=.1))
        output = io.StringIO()
        with patch.object(reap, 'probe_once', side_effect=outcomes) as once, \
                patch.object(reap.time, 'sleep') as sleep, contextlib.redirect_stdout(output):
            if misses == 5:
                try:
                    reap.probe(ROOT / 'bin', 'normal')
                except AssertionError as error:
                    assert str(error) == ('未能验证（测量环境问题，非产品缺陷）：机器负载过高，5 次都没能'
                                          '在产品 2 秒超时前建立观察窗口；模式=normal，各次读龄=[2.1, 2.1, 2.1, 2.1, 2.1]')
                else:
                    raise AssertionError('missed windows must not pass')
            else:
                result = reap.probe(ROOT / 'bin', 'normal')
                assert result['attempts'] == 3 and result['reader_ages'] == [2.1, 2.1, .1], result
            waits = [call.args[0] for call in sleep.call_args_list]
            assert waits == ([1, 2, 4, 8] if misses == 5 else [1, 2]), waits
            assert once.call_count == (5 if misses == 5 else 3), once.call_args_list
            lines = output.getvalue().splitlines()
            expected_waits = [1, 2, 4, 8, 0] if misses == 5 else [1, 2]
            assert len(lines) == misses and all(line.startswith('INCONCLUSIVE subscribe normal:') and
                   f'retry_wait={wait}s' in line for line, wait in zip(lines, expected_waits)), lines
    # The exported checkout is private: replace all five stage boundaries.
    stages = ['tests/smoke.sh', 'tests/review-identity.sh',
              'bin/qwb-lint.sh', 'tests/collab-all.sh']
    for index, stage in enumerate(stages):
        (ROOT / stage).write_text(f'''#!/usr/bin/env bash
set -eu
[[ "$QWB_FULL_GATE_REAP" == 1 ]]
if [[ "$GATE_CASE" == term ]]; then
  . "$PWD/tests/process-fixture.sh"
  qwb_test_scope "$@"
fi
printf '%s\\n' '{index}:stdout'
printf '%s\\n' '{index}:stderr' >&2
touch "$GATE_OBSERVER/{index}.ready"
while [[ ! -f "$GATE_OBSERVER/0.ready" || ! -f "$GATE_OBSERVER/1.ready" || ! -f "$GATE_OBSERVER/2.ready" || ! -f "$GATE_OBSERVER/3.ready" || "$GATE_CASE" == term ]]; do sleep .02; done
printf '%s\\n' '{index}:end'
touch "$GATE_OBSERVER/{index}.end"
[[ "$GATE_CASE" != '{index}' ]] || exit 7
''')
    (ROOT / 'tests/subscribe-reap.py').write_text('''import os,sys,time
from pathlib import Path
observer=Path(os.environ['GATE_OBSERVER'])
assert all((observer/f'{index}.end').exists() for index in range(4)), 'tail started before parallel stages ended'
print('4:stdout',flush=True)
print('4:stderr',file=sys.stderr,flush=True)
(observer/'4.ready').touch()
while os.environ['GATE_CASE']=='tail-term':time.sleep(.02)
print('4:end',flush=True)
sys.exit(7 if os.environ['GATE_CASE']=='4' else 0)
''')
    (ROOT / 'qwb.config.sh').write_text("QWB_GATE_FULL='bash tests/full-gate.sh'\n")
    expected = ''.join(f'{index}:stdout\n{index}:stderr\n{index}:end\n' for index in range(5))
    for interpreter in ['bash', '/bin/bash']:
        for case in ['success', '0', '3', '4', 'term', 'tail-term']:
            with tempfile.TemporaryDirectory(prefix='gate-observe-', dir=BASE) as temporary:
                observer = Path(temporary)
                env = dict(os.environ, GATE_CASE=case, GATE_OBSERVER=temporary)
                before = set(BASE.iterdir())
                interrupted = case in ['term', 'tail-term']
                command = [interpreter, 'tests/full-gate.sh'] if interrupted else [interpreter, 'bin/qwb-test.sh', 'full']
                process = subprocess.Popen(command, cwd=ROOT, env=env, stdout=subprocess.PIPE,
                                           stderr=subprocess.STDOUT, text=True)
                try:
                    if interrupted:
                        deadline = time.monotonic() + 20
                        count = 5 if case == 'tail-term' else 4
                        while not all((observer / f'{index}.ready').exists() for index in range(count)):
                            assert process.poll() is None, 'gate exited before target stages started'
                            assert time.monotonic() < deadline, 'target stages did not start'
                            time.sleep(.02)
                        process.terminate()
                    text, _ = process.communicate(timeout=20)
                    rc = process.returncode
                    assert rc == (143 if interrupted else 0 if case == 'success' else 1), (command, case, rc, text)
                    if not interrupted:
                        failure = 'FAIL  订阅子进程回收公开入口回归\n' if case == '4' else ''
                        assert text == expected + failure + ('' if case == 'success' else '门失败（full）：bash tests/full-gate.sh 退出码=1\n'), (case, text)
                    assert set(BASE.iterdir()) == before, (case, 'temporary directory survived')
                    assert not any(str(ROOT) in row[4] and row[0] != str(os.getpid())
                                   for row in snapshot()), (case, 'fixture process survived')
                    print(json.dumps(dict(full_gate=interpreter, case=case, rc=rc,
                                          ordered_output=True, new_directories=[]), ensure_ascii=False), flush=True)
                finally:
                    if process.poll() is None:
                        process.terminate()
                        process.communicate(timeout=20)


if __name__ == '__main__':
    if 'QWB_TEST_SOCKET_DIRS' not in os.environ:
        os.execv(sys.executable, [sys.executable, str(ROOT / 'tests/process_fixture.py'),
                                 '--command', sys.executable, __file__])

    def interrupted(signum, _frame):
        signal.signal(signum, signal.SIG_IGN)
        raise SystemExit(128 + signum)
    signal.signal(signal.SIGTERM, interrupted)
    signal.signal(signal.SIGINT, interrupted)
    # The unchanged directory/bytecode assertions must observe only this invocation.
    # A two-byte checkout name keeps nested fixture sockets within the 103-byte budget.
    while True:
        checkout = BASE / secrets.token_hex(1)
        try:
            checkout.mkdir(mode=0o700)
            with open(os.environ['QWB_TEST_SOCKET_DIRS'], 'a') as record:
                record.write(str(checkout) + '\n')
            break
        except FileExistsError:
            continue
    try:
        with subprocess.Popen(['git', '-C', str(ROOT), 'archive', 'HEAD'],
                              stdout=subprocess.PIPE) as archive:
            exported = subprocess.run(['tar', '-x', '-C', str(checkout)], stdin=archive.stdout)
            archive.stdout.close()
            if archive.wait() or exported.returncode:
                raise RuntimeError('源码导出失败')
        ROOT = checkout
        BASE = ROOT / '.qwb-tmp'
        BASE.mkdir(exist_ok=True)
        WIRE = str(ROOT / 'tests/fixtures/herdr/wire-server.py')
        check(['bash', 'tests/smoke.sh', 'root-tab-missing'])
        check(['/bin/bash', 'tests/smoke.sh', 'root-tab-missing'])
        check(['bash', 'tests/smoke.sh', 'root-tab-missing'], interrupt=True)
        check(['bash', 'tests/smoke.sh'], interrupt=True)
        check(['bash', 'tests/collab-handoff.sh'], interrupt=True, ready='handoff')
        check(['/bin/bash', 'tests/full-gate.sh'], interrupt=True)
        check_full_gate()
        print('PROCESS ENTRY CLEANUP PASS')
    finally:
        shutil.rmtree(checkout)
