#!/usr/bin/env python3
"""Verify public entries themselves drain their fixture processes, including stdin scripts."""
import json
import os
from pathlib import Path
import secrets
import shutil
import signal
import subprocess
import sys
import tempfile
import time

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / '.qwb-tmp'
BASE.mkdir(exist_ok=True)
WIRE = str(ROOT / 'tests/fixtures/herdr/wire-server.py')


def snapshot():
    probe = subprocess.Popen(['/bin/ps', '-axo', 'pid=,ppid=,pgid=,stat=,command='],
                             stdout=subprocess.PIPE)
    output, _ = probe.communicate()
    assert probe.returncode == 0
    return [row for line in output.decode('utf-8', errors='replace').splitlines() if (row := line.split(None, 4))
            and int(row[0]) != probe.pid]


def check(command, interrupt=False, ready='wire'):
    groups = set()
    observed = {}
    with tempfile.TemporaryDirectory(prefix='observe-', dir=BASE) as temporary:
        observer = Path(temporary)
        wire_record = observer / 'wire.json'
        shim = observer / 'python3'
        # Observe the actual exec PID/group, without starting another supervisor around the entry.
        shim.write_text(f'''#!{sys.executable}
import json,os,sys
from pathlib import Path
if sys.argv[1:3]==['-B',os.environ['ENTRY_WIRE']]:
    Path(os.environ['ENTRY_WIRE_RECORD']).write_text(json.dumps(dict(pid=os.getpid(),ppid=os.getppid(),pgid=os.getpgrp(),argv=sys.argv[1:])))
os.execv(sys.executable,[sys.executable,*sys.argv[1:]])
''')
        shim.chmod(0o755)
        env = dict(os.environ, PATH=str(observer) + ':' + os.environ['PATH'],
                   ENTRY_WIRE=WIRE, ENTRY_WIRE_RECORD=str(wire_record))
        before = set(BASE.iterdir())
        with tempfile.TemporaryFile(dir=BASE) as output:
            process = subprocess.Popen(command, cwd=ROOT, env=env, stdout=output,
                                       stderr=subprocess.STDOUT, start_new_session=True)
            groups.add(process.pid)
            try:
                deadline = time.monotonic() + 60
                sent = False
                while process.poll() is None:
                    table = snapshot()
                    owned = {int(row[0]) for row in table if int(row[2]) in groups}
                    while True:
                        grown = owned | {int(row[0]) for row in table if int(row[1]) in owned}
                        if grown == owned:
                            break
                        owned = grown
                    for row in table:
                        if int(row[0]) in owned:
                            groups.add(int(row[2]))
                            observed[int(row[0])] = row
                    text = os.pread(output.fileno(), os.fstat(output.fileno()).st_size, 0).decode(
                        'utf-8', 'backslashreplace')
                    if ready == 'wire':
                        reached = wire_record.exists()
                    elif ready == 'handoff':
                        reached = 'PASS 跨交付崩溃仍有持久待办' in text
                    else:
                        reached = any(int(row[0]) in owned and str(ROOT) in row[4]
                                      and ('/bin/qwb-' in row[4] or '/qwbuddy/bin/qwb-' in row[4])
                                      for row in table)
                    if interrupt and reached and not sent:
                        time.sleep(.15)
                        process.send_signal(signal.SIGTERM)
                        sent = True
                    assert time.monotonic() < deadline, (command, 'entry timed out', text[-2000:])
                    time.sleep(.02)
                rc = process.wait()
                assert rc == (143 if interrupt else 0), (command, rc)
                assert not interrupt or sent, 'entry exited before its interruption point'
                wire = json.loads(wire_record.read_text()) if wire_record.exists() else None
                assert ready != 'wire' or wire, ('wire fixture was never launched', command)
                if wire:
                    groups.add(wire['pgid'])
                if interrupt:
                    time.sleep(5)
                survivors = [row for row in snapshot() if int(row[2]) in groups
                             and not row[3].startswith('Z')]
                text = os.pread(output.fileno(), os.fstat(output.fileno()).st_size, 0).decode(
                    'utf-8', 'backslashreplace')
                assert not survivors, (command, 'owned processes survived', survivors)
                assert not any(line.startswith('rm:') for line in text.splitlines()), text
                assert set(BASE.iterdir()) == before, (command, 'temporary directory survived',
                    {str(p): [str(q.relative_to(p)) for q in list(p.rglob('*'))[:20]]
                     for p in set(BASE.iterdir()) - before})
                assert not (ROOT / 'tests/__pycache__').exists(), 'test imports generated bytecode'
                print(json.dumps(dict(command=command, term=interrupt, rc=rc,
                                      recorded_groups=sorted(groups), wire=wire, survivors=survivors,
                                      new_directories=[], bytecode=False, tail=text.splitlines()[-5:]),
                                 ensure_ascii=False), flush=True)
            finally:
                if process.poll() is None:
                    process.terminate()
                    process.wait(timeout=20)
                # On a failed check, stop only exact observed owned process incarnations.
                if wire_record.exists():
                    wire = json.loads(wire_record.read_text())
                    groups.add(wire['pgid'])
                for row in snapshot():
                    old = observed.get(int(row[0]))
                    owned_wire = wire_record.exists() and int(row[0]) == wire['pid'] and int(row[2]) == wire['pgid']
                    if owned_wire or (old and row[2] == old[2] and row[4] == old[4] and int(row[2]) in groups):
                        try:
                            os.kill(int(row[0]), signal.SIGTERM)
                        except ProcessLookupError:
                            pass


def check_full_gate():
    # The exported checkout is private: replace only the four stage boundaries.
    stages = ['tests/smoke.sh', 'tests/review-identity.sh',
              'bin/qwb-lint.sh', 'tests/collab-all.sh']
    for index, stage in enumerate(stages):
        (ROOT / stage).write_text(f'''#!/usr/bin/env bash
set -eu
if [[ "$GATE_CASE" == term ]]; then
  . "$PWD/tests/process-fixture.sh"
  qwb_test_scope "$@"
fi
printf '%s\\n' '{index}:stdout'
printf '%s\\n' '{index}:stderr' >&2
touch "$GATE_OBSERVER/{index}.ready"
while [[ ! -f "$GATE_OBSERVER/0.ready" || ! -f "$GATE_OBSERVER/1.ready" || ! -f "$GATE_OBSERVER/2.ready" || ! -f "$GATE_OBSERVER/3.ready" || "$GATE_CASE" == term ]]; do sleep .02; done
printf '%s\\n' '{index}:end'
[[ "$GATE_CASE" != '{index}' ]] || exit 7
''')
    (ROOT / 'qwb.config.sh').write_text("QWB_GATE_FULL='bash tests/full-gate.sh'\n")
    expected = ''.join(f'{index}:stdout\n{index}:stderr\n{index}:end\n' for index in range(4))
    for interpreter in ['bash', '/bin/bash']:
        for case in ['success', '0', '3', 'term']:
            with tempfile.TemporaryDirectory(prefix='gate-observe-', dir=BASE) as temporary:
                observer = Path(temporary)
                env = dict(os.environ, GATE_CASE=case, GATE_OBSERVER=temporary)
                before = set(BASE.iterdir())
                command = [interpreter, 'tests/full-gate.sh'] if case == 'term' else [interpreter, 'bin/qwb-test.sh', 'full']
                process = subprocess.Popen(command, cwd=ROOT, env=env, stdout=subprocess.PIPE,
                                           stderr=subprocess.STDOUT, text=True)
                try:
                    if case == 'term':
                        deadline = time.monotonic() + 20
                        while not all((observer / f'{index}.ready').exists() for index in range(4)):
                            assert process.poll() is None, 'gate exited before all stages started'
                            assert time.monotonic() < deadline, 'stages did not run concurrently'
                            time.sleep(.02)
                        process.terminate()
                    text, _ = process.communicate(timeout=20)
                    rc = process.returncode
                    assert rc == (143 if case == 'term' else 0 if case == 'success' else 1), (command, case, rc, text)
                    if case != 'term':
                        assert text == expected + ('' if case == 'success' else '门失败（full）：bash tests/full-gate.sh 退出码=1\n'), (case, text)
                    assert set(BASE.iterdir()) == before, (case, 'temporary directory survived')
                    assert not any(str(ROOT) in row[4] and row[0] != str(os.getpid())
                                   for row in snapshot()), (case, 'fixture process survived')
                    print(json.dumps(dict(full_gate=interpreter, case=case, rc=rc,
                                          ordered_output=True, new_directories=[]), ensure_ascii=False), flush=True)
                finally:
                    if process.poll() is None:
                        process.terminate()
                        process.communicate(timeout=20)


if __name__ == '__main__':
    if 'QWB_TEST_SOCKET_DIRS' not in os.environ:
        os.execv(sys.executable, [sys.executable, str(ROOT / 'tests/process_fixture.py'),
                                 '--command', sys.executable, __file__])

    def interrupted(signum, _frame):
        signal.signal(signum, signal.SIG_IGN)
        raise SystemExit(128 + signum)
    signal.signal(signal.SIGTERM, interrupted)
    signal.signal(signal.SIGINT, interrupted)
    # The unchanged directory/bytecode assertions must observe only this invocation.
    # A two-byte checkout name keeps nested fixture sockets within the 103-byte budget.
    while True:
        checkout = BASE / secrets.token_hex(1)
        try:
            checkout.mkdir(mode=0o700)
            with open(os.environ['QWB_TEST_SOCKET_DIRS'], 'a') as record:
                record.write(str(checkout) + '\n')
            break
        except FileExistsError:
            continue
    try:
        with subprocess.Popen(['git', '-C', str(ROOT), 'archive', 'HEAD'],
                              stdout=subprocess.PIPE) as archive:
            exported = subprocess.run(['tar', '-x', '-C', str(checkout)], stdin=archive.stdout)
            archive.stdout.close()
            if archive.wait() or exported.returncode:
                raise RuntimeError('源码导出失败')
        ROOT = checkout
        BASE = ROOT / '.qwb-tmp'
        BASE.mkdir(exist_ok=True)
        WIRE = str(ROOT / 'tests/fixtures/herdr/wire-server.py')
        check(['bash', 'tests/smoke.sh', 'root-tab-missing'])
        check(['/bin/bash', 'tests/smoke.sh', 'root-tab-missing'])
        check(['bash', 'tests/smoke.sh', 'root-tab-missing'], interrupt=True)
        check(['bash', 'tests/smoke.sh'], interrupt=True)
        check(['bash', 'tests/collab-handoff.sh'], interrupt=True, ready='handoff')
        check(['/bin/bash', 'tests/full-gate.sh'], interrupt=True)
        check_full_gate()
        print('PROCESS ENTRY CLEANUP PASS')
    finally:
        shutil.rmtree(checkout)
